# Generated by Django 4.2.23 on 2025-09-30 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user_quiz_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insertionsortresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='selectionsortresult',
            name='user',
        ),
        migrations.RemoveField(
            model_name='snakegameprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='typetestprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='BubbleSortResult',
        ),
        migrations.DeleteModel(
            name='InsertionSortResult',
        ),
        migrations.DeleteModel(
            name='SelectionSortResult',
        ),
        migrations.DeleteModel(
            name='SnakeGameProgress',
        ),
        migrations.DeleteModel(
            name='TypeTestProgress',
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
