# Generated by Django 4.2.23 on 2025-10-25 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_insertionsortresult_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalistLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('time_elapsed', models.IntegerField(help_text='Time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galist_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Galist Leaderboard Entry',
                'verbose_name_plural': 'Galist Leaderboard Entries',
                'ordering': ['-score', 'time_elapsed'],
            },
        ),
    ]
